#!/bin/bash
while [ "$#" -gt 0 ]; do
    case "$1" in
        -h|--help)
            sed -n '/^while/,/^done/p' "$0" | grep -oP '\S+(?=\)$)'
            exit 0
            ;;
        -l|--list)
            list=1
            shift
            ;;
        *)
            if [ -z "$deck" ]; then
                deck="$1"
                shift
            elif [ -z "$entity" ]; then
                entity="$1"
                shift
            else
                break
            fi
            ;;
    esac
done


if [ -n "$list" ] && [ -n "$deck" ]; then
    python -m cli json-file "$deck" --help
elif [ -n "$list" ]; then
    python -m cli json-file --help
else
    python -m cli json-file "$deck" "$entity" "/var/www/files/xfer/${deck}_${entity}.json"
fi
