#!/bin/bash

prefix="."
tts_prefix="/mnt/c/Users/Med/Documents/My Games/Tabletop Simulator/Saves/Saved Objects"
mancer_prefix="/var/www/files/deck"


while [ "$#" -gt 0 ]; do
    case "$1" in
        -h|--help)
            sed -n '/^while/,/^done/p' "$0" | grep -oP '\S+(?=\)$)'
            exit 0
            ;;
        -l|--list)
            list=1
            shift
            ;;
        -t|--tts)
            prefix="$tts_prefix"
            shift
            ;;
        -m|--mancer)
            prefix="$mancer_prefix"
            shift
            ;;
        -p|--prefix)
            prefix="$2"
            shift 2
            ;;
        *)
            if [ -z "$deck" ]; then
                deck="$1"
                shift
            elif [ -z "$entity" ]; then
                entity="$1"
                shift
            else
                break
            fi
            ;;
    esac
done


if [ -n "$list" ] && [ -n "$deck" ]; then
    python -m cli json-file "$deck" --help
elif [ -n "$list" ]; then
    python -m cli json-file --help
else
    outpath="$prefix/${deck}_${entity}.json"
    python -m cli json-file "$deck" "$entity" "$outpath"
    echo "$outpath" >&2
fi
